[project]
name = "the_aichemist_codex"
version = "0.1.0"
description = "A modular file and project management system."
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
  # Core Dependencies
  "EbookLib>=0.17.1",
  "Kreuzberg>=0.1.0",
  "PyYAML>=6.0.1",
  "aiofiles>=24.1.0",
  "annotated-types>=0.7.0",
  "attrs>=25.1.0",
  "click>=8.1.8",
  "colorama>=0.4.6",
  "dynaconf>=3.2.10",
  "ezdxf>=1.0.0",
  "fastjsonschema>=2.21.1",
  "importlib_metadata>=8.6.1",
  "iniconfig>=2.0.0",
  "jsonschema-specifications>=2024.10.1",
  "jsonschema>=4.23.0",
  "jupyter_core>=5.7.2",
  "lxml>=4.9.3",
  "nbformat>=5.10.4",
  "odfpy>=1.4.1",
  "openpyxl>=3.1.0",
  "packaging>=24.2",
  "pandas>=2.0.0",
  "platformdirs>=4.3.6",
  "pluggy>=1.5.0",
  "psutil>=7.0.0",
  "pydantic>=2.10.6",
  "pydantic_core>=2.27.2",
  "pypdf>=3.17.1",
  "python-docx>=0.8.11",
  "python-dotenv>=1.0.1",
  "python-magic-bin>=0.4.14; sys_platform == 'win32'",
  "rarfile>=4.0",
  "rapidfuzz>=2.15.1",
  "referencing>=0.36.2",
  "reportlab>=4.0.4",
  "rich>=13.6.0",
  "rpds-py>=0.23.1",
  "setuptools>=75.8.0",
  "structlog>=25.1.0",
  "tenacity>=9.0.0",
  "tiktoken>=0.5.1",
  "tomli>=2.0.1",
  "traitlets>=5.14.3",
  "typing_extensions>=4.12.2",
  "watchdog>=3.0.0",
  "whoosh>=2.7.4",
  "xmltodict>=0.13.0",
  "zipp>=3.21.0",
  # AI & NLP
  "sentence-transformers>=2.2.2",
  "faiss-cpu>=1.7.4",
  "pytesseract>=0.3.10",
  "openai>=1.3.5",
  # Search & Indexing
  "sqlite-utils>=3.36.0",
  "sqlalchemy>=2.0.23",
  "fastapi>=0.111.0",
  # Security & Compliance
  "cryptography>=41.0.7",
  "pyjwt>=2.7.0",
  "bcrypt>=4.1.2",
  "casbin>=1.38.0",
  "loguru>=0.7.2",
  "py7zr>=0.22.0",
  "aiosqlite>=0.21.0",
]

[project.optional-dependencies]
dev = [
  "Pygments>=2.18.0",
  "black>=24.8.0",
  "build>=1.2.1",
  "codecov>=2.1.13",
  "ipykernel>=6.29.5",
  "ipython>=8.18.1",
  "isort>=5.13.2",
  "mypy-extensions>=1.0.0",
  "mypy>=1.11.1",
  "nbqa>=1.8.7",
  "mkdocs-material>=9.5.33",
  "mkdocs>=1.6.0",
  "mkdocstrings-python>=1.10.8",
  "mkdocstrings>=0.25.2",
  "pre-commit>=3.8.0",
  "pytest-asyncio>=0.25.3",
  "pytest-benchmark>=4.0.0",
  "pytest-cov>=6.0.0",
  "pytest-mock>=3.14.0",
  "pytest>=8.3.4",
  "ruff>=0.6.2",
  "setuptools>=73.0.1",
  "sphinx-autodoc-typehints>=1.22.0",
  "sphinx-copybutton>=0.5.2",
  "sphinx-rtd-theme>=2.0.0",
  "sphinx>=6.2.1",
  "sphinxcontrib-mermaid>=0.9.2",
  "twine>=5.1.0",
  "virtualenv>=20.26.3",
]

[project.scripts]
codex = "aichemist_codex.cli_interface:main"

[build-system]
requires = ["setuptools>=75.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["backend/src"]
include = [
  "file_reader*",
  "file_manager*",
  "search*",
  "logging*",
  "rollback*",
  "security*",
  "ai*",
  "integration*",
  "ui*",
  "utils*",
  "config*",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["backend/src"]
asyncio_mode = "auto"
tmp_path_retention_count = 2
tmp_path_retention_policy = "failed"
addopts = "--basetemp=./tmp"


[tool.ruff]
include = ["pyproject.toml", "src/**/*.py", "scripts/**/*.py"]

exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[dependency-groups]
dev = ["pytest>=8.3.4", "python-magic-bin>=0.4.14"]
