[project]
name = "the_aichemist_codex"
version = "0.1.0"
description = "A modular file and project management system."
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "aiofiles",    # Async file I/O
    "tiktoken",     # Token counting
    "tomli",        # Config parsing
    "nbformat"      # Notebook validation (optional)
]

[project.scripts]
codex = "the_aichemist_codex.cli.main:main"

[project.entry-points."codex.plugins"]
# External plugins will register entry points here.
# Example:
# fancy = "fancy_plugin:display_function"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
